version: '3'

networks:
  openhim:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openempi-db:
    container_name: openempi-db_demo
    image: uwitech/postgresql
    volumes:
        - cr-pgdata:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=openempi
        - POSTGRES_DB=openempi
        - POSTGRES_PASSWORD=openempi
    ports:
        - 5432:5432


  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
  
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  openempi-app:
    container_name: openempi-demo
    env_file: .env
    image: uwitech/ohie-cr
    ports:
        - 8081:8080
        - 3600:3600
        - 3700:3700
    volumes:
        - cr-orientdata:/data
    depends_on:
        - openempi-db
    

volumes:
  mongo-data:
  cr-pgdata:
  cr-orientdata: